create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contacts enable row level security;
